# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jatin Shah
tagline:          
url:              http://jatinshah.github.io
paginate:         1
baseurl:          /
author:
  name:           Jatin Shah
  url:            https://twitter.com/jatinshah
  email:          jatindshah@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jatinshah/jatinshah.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
