title: Jatin Shah
email: jatin@blockpunk.net
description: Jatin Shah's website
url: "https://jatinshah.org"
twitter: jatinshah

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed